# Generated by Django 4.2.6 on 2023-11-07 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Principal', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estudiante',
            old_name='email',
            new_name='correo',
        ),
    ]
