# Generated by Django 4.2.6 on 2023-11-07 14:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Principal', '0002_rename_email_estudiante_correo'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='fechaNacimiento',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
